apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-topicprovider
  namespace: crossplane-system
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane/provider-mqttprovider
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A template that can be used to create Crossplane providers.
spec:
  ignoreCrossplaneConstraints: true
  package: docker.io/davitazzio/topic-provider
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  controllerConfigRef: 
    name: enable-ess
  # serviceAccountName: crossplane-account

---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: enable-ess
spec:
  serviceAccountName: crossplane-account
  args:
    - --debug
---
