apiVersion: apiextensions.crossplane.io/vl
kind: Composition
metadata:
  name: topic-provatopicprovider
spec:
  compositeTypeRef:
    apiVersion: slices.crossplane.io/vlalphal
    kind: xtopic6
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
  resources:
    - name: cr-topic
      base:
        apiVersion: topic.topicprovider.crossplane.io/v1alpha1
        kind: MqttTopic
        spec:
          forProvider:
              name: "provatopicprovider"
              host: "as-sensiblecity1.cloudmmwunibo.it"
              username: "77516558eb5b721f"
              password: "o9CYsHQ8VPTQ26ZkiylQ8c6Obd61nNEetQi1DKEDBJzC"
          providerConfigRef:
            name: example
      patches:
      - type: PatchSet
        patchSetName: metadata
      - fromFieldPath: spec.degradedtreshold
        toFieldPath: spec.forProvider.degraded_treshold
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.name
      - fromFieldPath: spec.host
        toFieldPath: spec.forProvider.host
      - fromFieldPath: spec.username
        toFieldPath: spec.forProvider.username
      - fromFieldPath: spec.password
        toFieldPath: spec.forProvider.password

    - name: kubernetes-broker
      base:
        apiVersion: apps.emqx.io/v2beta1
        kind: EMQX
        metadata:
          name: emqx
        spec:
          image: emqx:5
      patches:
      - fromFieldPath: spec.host
        toFieldPath: spec.forProvider.host
      - fromFieldPath: spec.username
        toFieldPath: spec.bootstrapAPIKeys[0].key
      - fromFieldPath: spec.password
        toFieldPath: spec.bootstrapAPIKeys[0].secret

